-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 10:31:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UiPathprojekti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UiPathprojekti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UiPathprojekti` DEFAULT CHARACTER SET utf8 ;
USE `UiPathprojekti` ;

-- -----------------------------------------------------
-- Table `UiPathprojekti`.`InvoiceStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UiPathprojekti`.`InvoiceStatus` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UiPathprojekti`.`InvoiceHeader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UiPathprojekti`.`InvoiceHeader` (
  `invoicenumber` INT NOT NULL,
  `companyname` VARCHAR(100) NULL,
  `companycode` VARCHAR(45) NULL,
  `referencenumber` VARCHAR(45) NULL,
  `invoicedate` DATE NULL,
  `duedate` DATE NULL,
  `bankaccountnumber` VARCHAR(30) NULL,
  `amounttextvat` DECIMAL(10,2) NULL,
  `vat` DECIMAL(10,2) NULL,
  `totalamount` DECIMAL(10,2) NULL,
  `comments` VARCHAR(100) NULL,
  `InvoiceStatus_id` INT NOT NULL,
  PRIMARY KEY (`invoicenumber`),
  INDEX `fk_InvoiceHeader_InvoiceStatus1_idx` (`InvoiceStatus_id` ASC) VISIBLE,
  CONSTRAINT `fk_InvoiceHeader_InvoiceStatus1`
    FOREIGN KEY (`InvoiceStatus_id`)
    REFERENCES `UiPathprojekti`.`InvoiceStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UiPathprojekti`.`InvoiceRow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UiPathprojekti`.`InvoiceRow` (
  `rownumber` INT NOT NULL,
  `description` VARCHAR(100) NULL,
  `quantity` DECIMAL(10,2) NULL,
  `unit` VARCHAR(45) NULL,
  `unitprice` DECIMAL(10,2) NULL,
  `vatpercent` DECIMAL(10,2) NULL,
  `vat` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) NULL,
  `InvoiceHeader_invoicenumber` INT NOT NULL,
  PRIMARY KEY (`rownumber`, `InvoiceHeader_invoicenumber`),
  INDEX `fk_InvoiceRow_InvoiceHeader_idx` (`InvoiceHeader_invoicenumber` ASC) VISIBLE,
  CONSTRAINT `fk_InvoiceRow_InvoiceHeader`
    FOREIGN KEY (`InvoiceHeader_invoicenumber`)
    REFERENCES `UiPathprojekti`.`InvoiceHeader` (`invoicenumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
